name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop  # Trigger analysis for overall project statistics after merging
  pull_request:
    branches:
      - main
      - develop  # Trigger analysis for PRs before merging into develop or main
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          # fetch-depth: 0 is required. SonarCloud needs the full commit history 
          # to analyze "New Code" in Pull Requests properly.
          fetch-depth: 0  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version used in your project

      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Testing step. Uncomment if you have configured the generation of coverage/lcov.info
      # - name: Run tests and generate coverage report
      #   run: npm run test -- --no-watch --code-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 #7.0.0
        env:
          # GITHUB_TOKEN is provided automatically by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SONAR_TOKEN must be added in repository Settings -> Secrets and variables -> Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}